
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgcfrtwndiuomqvocxow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnY2ZydHduZGl1b21xdm9jeG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNjYzMDEsImV4cCI6MjA2MDk0MjMwMX0.EsDVmPmyNxpXSsLCvm5V0wVj-zp7ltn4sWxE-6TZcCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Force TypeScript to recognize the site_settings table
// This is a temporary workaround until you regenerate types
declare module '@/integrations/supabase/types' {
  interface Database {
    public: {
      Tables: {
        site_settings: {
          Row: {
            id: string;
            key: string;
            value: any;
            description: string | null;
            category: string;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            key: string;
            value: any;
            description?: string | null;
            category: string;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            key?: string;
            value?: any;
            description?: string | null;
            category?: string;
            created_at?: string;
            updated_at?: string;
          };
        };
      };
    };
  }
}
