
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msdvgjnugglqyjblbbgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZHZnam51Z2dscXlqYmxiYmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDczMDMsImV4cCI6MjA1NzgyMzMwM30.nX3ZKn9p1pftJNy7dEFCnbqTwRENqycAbRmDZMBQFG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    fetch: (url, options) => fetch(url, {
      ...options,
      cache: 'no-store',
    }),
    headers: {
      'x-supabase-cache-control': '0'
    }
  }
});
